trigger:
  branches:
    include:
      - master
  paths:
    include:
      - zipkin/**

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'zipkin'
  acrLoginServer: 'mytodosacr.azurecr.io'
  dockerRegistryServiceConnection: 'acr-connection' # Docker Registry SC name
  resourceGroup: 'TallerPipelines'
  azureWebAppName: 'todo-zipkin'                 # Azure Web App name
  azureSubscription: 'PipelineConnection'        # ARM SC name

stages:

  - stage: Deploy
    displayName: Deploy to Azure Web App
    jobs:
      - job: DeployWebApp
        steps:
          - task: AzureCLI@2
            inputs:
              azureSubscription: $(azureSubscription)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                az webapp config container set \
                  --name $(azureWebAppName) \
                  --resource-group $(resourceGroup) \
                  --docker-custom-image-name openzipkin/zipkin:latest \
                  --docker-registry-server-url https://index.docker.io
          - task: AzureCLI@2
            displayName: Set WEBSITES_PORT App Setting
            inputs:
              azureSubscription: $(azureSubscription)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                echo "Setting WEBSITES_PORT to 9411..."
                az webapp config appsettings set \
                  --name $(azureWebAppName) \
                  --resource-group $(resourceGroup) \
                  --settings WEBSITES_PORT=9411
                  