trigger:
  branches:
    include:
      - master
  paths:
    include:
      - zipkin/**

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'zipkin'
  acrLoginServer: 'mytodosacr.azurecr.io'
  dockerRegistryServiceConnection: 'acr-connection' # Docker Registry SC name
  azureWebAppName: 'todo-zipkin'                 # Azure Web App name
  azureSubscription: 'PipelineConnection'        # ARM SC name

stages:

  - stage: Deploy
    displayName: Deploy to Azure Web App
    jobs:
      - job: DeployWebApp
        steps:
          - task: AzureWebAppContainer@1
            displayName: Deploy image to Azure Web App
            inputs:
              azureSubscription: $(azureSubscription)
              appName: $(azureWebAppName)
              
              containers: |
                'openzipkin/zipkin:latest'