pool:
  vmImage: 'ubuntu-latest'

variables:
  KEY_VAULT_NAME: 'todo-key-vault'
  CERT_NAME: 'tls-cert'
  KEY_NAME: 'tls-key'

stages:
  - stage: GenerateTLS
    displayName: 'Generate and Upload TLS Certificate'
    jobs:
      - job: GenerateCert
        steps:
          - task: AzureCLI@2
            inputs:
              azureSubscription: 'PipelineConnection'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                echo "Generating TLS certificate..."

                openssl req -x509 -nodes -days 365 \
                  -newkey rsa:2048 \
                  -keyout tls.key \
                  -out tls.crt \
                  -subj "/CN=demo.local"

                echo "Uploading certificate to Key Vault..."
                az keyvault secret set --vault-name $KEY_VAULT_NAME \
                  --name $CERT_NAME \
                  --file tls.crt

                echo "Uploading key to Key Vault..."
                az keyvault secret set --vault-name $KEY_VAULT_NAME \
                  --name $KEY_NAME \
                  --file tls.key

                echo "TLS certificate and key uploaded successfully."

            displayName: 'Generate TLS Cert and Upload to Key Vault'