trigger:
  branch:
    include:
      - master
  paths:
    include:
      - auth-api/**

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'auth-api'
  acrLoginServer: 'mytodosacr.azurecr.io'
  dockerRegistryServiceConnection: 'acr-connection' # Docker Registry SC name
  azureWebAppName: 'TODO-AUTH-API'                 # Azure Web App name
  azureSubscription: 'PipelineConnection'        # ARM SC name
  USERS_API_ADDRESS: https://users-api-fqf5b6eycxc5fzdf.eastus-01.azurewebsites.net
  ZIPKIN_URL: https://todo-zipkin-gqbcbmezgcbddwat.eastus-01.azurewebsites.net

stages:
  - stage: BuildAndPush
    displayName: Build and Push Docker Image  
    jobs:
      - checkout: self
        displayName: Checkout Master Branch
        inputs:
          ref: refs/heads/master
          
      - job: Docker
        steps:
          - task: Docker@2
            displayName: Build and push image to ACR
            inputs:
              containerRegistry: $(dockerRegistryServiceConnection)
              repository: $(imageName)
              command: buildAndPush
              Dockerfile: auth-api/Dockerfile
              buildContext: auth-api
              tags: |
                $(Build.BuildId)

  - stage: Deploy
    displayName: Deploy to Azure Web App
    dependsOn: BuildAndPush
    jobs:
      - job: DeployWebApp
        steps:
          - task: AzureWebAppContainer@1
            displayName: Deploy image to Azure Web App
            inputs:
              azureSubscription: $(azureSubscription)
              appName: $(azureWebAppName)
              envVars: |
                USERS_API_ADDRESS=$(USERS_API_ADDRESS)
                ZIPKIN_URL=$(ZIPKIN_URL)
              containers: |
                $(acrLoginServer)/$(imageName):$(Build.BuildId)
