services:
  log-message-processor:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - REDIS_HOST=todo-redis.redis.cache.windows.net

      - REDIS_PORT=6379
      - REDIS_CHANNEL=log_channel
    networks:
      - microservice-network
networks:
  microservice-network:
    driver: bridge